apiVersion: apps/v1
kind: Deployment
metadata:
  name: $REPO_SLUG-$SERVER_ENV
  namespace: $K8S_NAMESPACE
  labels:
    app: $REPO_SLUG-$SERVER_ENV
spec:
  selector:
    matchLabels:
      app: $REPO_SLUG-$SERVER_ENV
  replicas: 1
  template:
    metadata:
      labels:
        app: $REPO_SLUG-$SERVER_ENV
    spec:
      containers:
      - name: nginx
        image: $BUILD_IMAGE
        ports:
        - containerPort: 3006
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: docker-registry-auth
---
apiVersion: v1
kind: Service
metadata:
  name: $REPO_SLUG-$SERVER_ENV-svc
  namespace: $K8S_NAMESPACE
spec:
  ports:
  - port: 3006
    targetPort: 3006
    protocol: TCP
  selector:
    app: $REPO_SLUG-$SERVER_ENV